# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f6337357851f35b32e2cf6a6fb7de64aefdd1dd6ed3c8717fa68a0ac5740a79b18472e06decc52287c402da40cbc89556c7af22c7aab436edc0e23052e69af41

test:
  secret_key_base: d4cbdd19c4a297c59ba17bd451168ce5bc32a80a327e6c863f9c12b3b936123737a0a2227935716da082ce2a0f40daec7f503d1971c6affcbb40b317379dab74

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
